apiVersion: v1
kind: Service
metadata:
  name: helloweb
  labels:
    app: helloweb
spec:
  type: NodePort
  selector:
    app: helloweb
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888     